(function($, wp) {
    wp.customize('monawp_presets_panel_header_preset_select', function(value) {
        value.bind(function(newVal) {
            var palettes = {
				'0': {'monawp_header_panel_builder_0':'row-start',
				'monawp_header_panel_builder_1':'monawp_site_logo_header',
				'monawp_header_panel_builder_2':'monawp_site_title_header',
				'monawp_header_panel_builder_3':'monawp_site_description_header',
				'monawp_header_panel_builder_4':'monawp_horizontal_menu_header',
				'monawp_header_panel_builder_5':'wrapper-end',
				'monawp_header_panel_builder_6':'row-start',
				'monawp_header_panel_builder_7':'monawp_socials_header',
				'monawp_header_panel_builder_8':'monawp_search_header',
				'monawp_header_panel_builder_9':'wrapper-end',
				'monawp_header_panel_builder_10':'',
				'monawp_header_panel_builder_11':'',
				'monawp_header_panel_builder_12':'',
				'monawp_header_panel_builder_13':'',
				'monawp_header_panel_builder_14':'',
				'monawp_header_panel_builder_15':'',
				'monawp_header_panel_builder_16':'',
				'monawp_header_panel_builder_17':'',
				},
				'1': {'monawp_header_panel_builder_0':'row-start',
				'monawp_header_panel_builder_1':'monawp_site_logo_header',
				'monawp_header_panel_builder_2':'monawp_site_title_header',
				'monawp_header_panel_builder_3':'monawp_site_description_header',
				'monawp_header_panel_builder_4':'monawp_horizontal_menu_header',
				'monawp_header_panel_builder_5':'wrapper-end',
				'monawp_header_panel_builder_6':'row-start',
				'monawp_header_panel_builder_7':'monawp_search_header',
				'monawp_header_panel_builder_8':'monawp_socials_header',
				'monawp_header_panel_builder_9':'wrapper-end',
				'monawp_header_panel_builder_10':'',
				'monawp_header_panel_builder_11':'',
				'monawp_header_panel_builder_12':'',
				'monawp_header_panel_builder_13':'',
				'monawp_header_panel_builder_14':'',
				'monawp_header_panel_builder_15':'',
				'monawp_header_panel_builder_16':'',
				'monawp_header_panel_builder_17':'',
				},
				'2': {'monawp_header_panel_builder_0':'row-start',
				'monawp_header_panel_builder_1':'monawp_site_logo_header',
				'monawp_header_panel_builder_2':'monawp_site_title_header',
				'monawp_header_panel_builder_3':'monawp_site_description_header',
				'monawp_header_panel_builder_4':'monawp_horizontal_menu_header',
				'monawp_header_panel_builder_5':'wrapper-end',
				'monawp_header_panel_builder_6':'col-start',
				'monawp_header_panel_builder_7':'monawp_search_header',
				'monawp_header_panel_builder_8':'monawp_socials_header',
				'monawp_header_panel_builder_9':'wrapper-end',
				'monawp_header_panel_builder_10':'',
				'monawp_header_panel_builder_11':'',
				'monawp_header_panel_builder_12':'',
				'monawp_header_panel_builder_13':'',
				'monawp_header_panel_builder_14':'',
				'monawp_header_panel_builder_15':'',
				'monawp_header_panel_builder_16':'',
				'monawp_header_panel_builder_17':'',
				},
				'3': {'monawp_header_panel_builder_0':'row-start',
				'monawp_header_panel_builder_1':'monawp_site_logo_header',
				'monawp_header_panel_builder_2':'monawp_site_title_header',
				'monawp_header_panel_builder_3':'monawp_site_description_header',
				'monawp_header_panel_builder_4':'monawp_socials_header',
				'monawp_header_panel_builder_5':'wrapper-end',
				'monawp_header_panel_builder_6':'row-start',
				'monawp_header_panel_builder_7':'monawp_horizontal_menu_header',
				'monawp_header_panel_builder_8':'monawp_search_header',
				'monawp_header_panel_builder_9':'wrapper-end',
				'monawp_header_panel_builder_10':'',
				'monawp_header_panel_builder_11':'',
				'monawp_header_panel_builder_12':'',
				'monawp_header_panel_builder_13':'',
				'monawp_header_panel_builder_14':'',
				'monawp_header_panel_builder_15':'',
				'monawp_header_panel_builder_16':'',
				'monawp_header_panel_builder_17':'',
				},
				'4': {
					'monawp_header_panel_builder_0': 'row-start',
					'monawp_header_panel_builder_1': 'monawp_site_title_header',
					'monawp_header_panel_builder_2': 'monawp_widget_1_header',
					'monawp_header_panel_builder_3': 'monawp_socials_header',
					'monawp_header_panel_builder_4': 'monawp_site_logo_header',
					'monawp_header_panel_builder_5': 'col-start',
					'monawp_header_panel_builder_6': 'monawp_search_header',
					'monawp_header_panel_builder_7': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_8': 'wrapper-end',
					'monawp_header_panel_builder_9': 'monawp_widget_2_header',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				'5': {
					'monawp_header_panel_builder_0': 'row-start',
					'monawp_header_panel_builder_1': 'monawp_site_title_header',
					'monawp_header_panel_builder_2': 'monawp_widget_1_header',
					'monawp_header_panel_builder_3': 'monawp_search_header',
					'monawp_header_panel_builder_4': 'monawp_socials_header',
					'monawp_header_panel_builder_5': 'monawp_site_logo_header',
					'monawp_header_panel_builder_6': 'wrapper-end',
					'monawp_header_panel_builder_7': 'col-start',
					'monawp_header_panel_builder_8': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_9': 'monawp_widget_2_header',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				'6': {
					'monawp_header_panel_builder_0': 'row-start',
					'monawp_header_panel_builder_1': 'monawp_widget_1_header',
					'monawp_header_panel_builder_2': 'monawp_site_title_header',
					'monawp_header_panel_builder_3': 'monawp_socials_header',
					'monawp_header_panel_builder_4': 'monawp_search_header',
					'monawp_header_panel_builder_5': 'monawp_site_logo_header',
					'monawp_header_panel_builder_6': 'wrapper-end',
					'monawp_header_panel_builder_7': 'col-start',
					'monawp_header_panel_builder_8': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_9': 'monawp_widget_2_header',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				'7': {
					'monawp_header_panel_builder_0': 'row-start',
					'monawp_header_panel_builder_1': '',
					'monawp_header_panel_builder_2': 'monawp_site_title_header',
					'monawp_header_panel_builder_3': '',
					'monawp_header_panel_builder_4': '',
					'monawp_header_panel_builder_5': 'monawp_site_logo_header',
					'monawp_header_panel_builder_6': 'wrapper-end',
					'monawp_header_panel_builder_7': 'col-start',
					'monawp_header_panel_builder_8': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_9': '',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				
				'8': {
					'monawp_header_panel_builder_0': 'row-start',
					'monawp_header_panel_builder_1': '',
					'monawp_header_panel_builder_2': '',
					'monawp_header_panel_builder_3': '',
					'monawp_header_panel_builder_4': '',
					'monawp_header_panel_builder_5': 'monawp_site_logo_header',
					'monawp_header_panel_builder_6': 'wrapper-end',
					'monawp_header_panel_builder_7': 'col-start',
					'monawp_header_panel_builder_8': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_9': '',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				
				'9': {
					'monawp_header_panel_builder_0': 'row-start',
					'monawp_header_panel_builder_1': '',
					'monawp_header_panel_builder_2': '',
					'monawp_header_panel_builder_3': '',
					'monawp_header_panel_builder_4': '',
					'monawp_header_panel_builder_5': 'monawp_site_logo_header',
					'monawp_header_panel_builder_6': 'wrapper-end',
					'monawp_header_panel_builder_7': 'col-start',
					'monawp_header_panel_builder_8': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_9': 'monawp_socials_header',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				'10': {
					'monawp_header_panel_builder_0': 'monawp_search_header',
					'monawp_header_panel_builder_1': '',
					'monawp_header_panel_builder_2': '',
					'monawp_header_panel_builder_3': '',
					'monawp_header_panel_builder_4': 'row-start',
					'monawp_header_panel_builder_5': 'monawp_site_logo_header',
					'monawp_header_panel_builder_6': 'wrapper-end',
					'monawp_header_panel_builder_7': 'row-start',
					'monawp_header_panel_builder_8': 'monawp_horizontal_menu_header',
					'monawp_header_panel_builder_9': 'monawp_socials_header',
					'monawp_header_panel_builder_10': 'wrapper-end',
					'monawp_header_panel_builder_11': '',
					'monawp_header_panel_builder_12': '',
					'monawp_header_panel_builder_13': '',
					'monawp_header_panel_builder_14': '',
					'monawp_header_panel_builder_15': '',
					'monawp_header_panel_builder_16': '',
					'monawp_header_panel_builder_17': '',
				},
				'11': {'monawp_header_panel_builder_0':'',
				'monawp_header_panel_builder_1':'',
				'monawp_header_panel_builder_2':'',
				'monawp_header_panel_builder_3':'',
				'monawp_header_panel_builder_4':'monawp_socials_header',
				'monawp_header_panel_builder_5':'',
				'monawp_header_panel_builder_6':'',
				'monawp_header_panel_builder_7':'monawp_horizontal_menu_header',
				'monawp_header_panel_builder_8':'monawp_searh_header',
				'monawp_header_panel_builder_9':'',
				'monawp_header_panel_builder_10':'monawp_site_logo_header',
				'monawp_header_panel_builder_11':'',
				'monawp_header_panel_builder_12':'',
				'monawp_header_panel_builder_13':'',
				'monawp_header_panel_builder_14':'',
				'monawp_header_panel_builder_15':'',
				'monawp_header_panel_builder_16':'',
				'monawp_header_panel_builder_17':'',
				},
            };

            var selectedPalette = palettes[newVal];
            $.each(selectedPalette, function(settingName, colorValue) {
                wp.customize(settingName).set(colorValue);
            });
        });
    });
})(jQuery, wp);
